version: '2'
services:
  webserver:
    build: webserver/.
    volumes:
      - ./webserver/logs:/var/log/nginx
  
  proxy:
    build: haproxy/.
    ports:
      - "80:80"
      - "443:443"

  mariadb-master:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306'
    volumes:
      - ./data:/bitnami
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_ROOT_PASSWORD=master_root_password
      - MARIADB_USER=my_user
      - MARIADB_PASSWORD=my_password
      - MARIADB_DATABASE=wordpress

  mariadb-slave:
    image: 'bitnami/mariadb:latest'
    ports:
      - '3306'
    depends_on:
      - mariadb-master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_REPLICATION_PASSWORD=repl_password
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=master_root_password

  maxscale:
    image: 'asosso/maxscale:2.1.9'
    volumes:
     - ./maxscale:/etc/maxscale.d
    ports:
      - '4006:4006'   #RW
      - '4008:4008'   #ReadOnly

